export const BUSINESS_INFO = {
  name: "SPARSHA CYBER CAFE & ONLINE SEVA KENDRA",
  tagline: "Your Trusted Digital Seva & Online Application Assistance Center in Aland",
  phone: "+91 7090161083",
  phonePrimary: "+91 7090161083",
  phoneSecondary: "+91 7483941814",
  whatsappRaw: "917090161083",
  whatsappNumber: "917090161083",
  email: "Shashikantkmali83@gmail.com",
  adminEmail: "siddumaindargi36@gmail.com",
  address: "Near Lingasayat Bhavan, M.K Sagri Complex, Aland, Karnataka 585302",
  plusCode: "HH78+Q27, Aland, Karnataka",
  googleMapsUrl: "https://www.google.com/maps/dir/?api=1&destination=Sparsha+Cyber+Cafe,+HH78%2BQ27,+Aland,+Karnataka",
  googleMapsEmbedUrl: "https://maps.google.com/maps?q=Sparsha+Cyber+Cafe,+HH78%2BQ27,+Aland,+Karnataka&t=&z=16&ie=UTF8&iwloc=&output=embed",
  hours: "Mon – Sun: 8:00 AM – 8:00 PM",
  workingHours: {
    weekdays: "8:00 AM – 8:00 PM",
    weekends: "8:00 AM – 8:00 PM",
    full: "Monday – Sunday: 8:00 AM – 8:00 PM",
  },
  keyServices: [
    "Kalyana-Karnataka 371(J) Certificates",
    "KCET / NEET / JEE Admission Counselling Assistance",
    "Bhoomi RTC Pahani & Mutation Extracts",
    "Nadakacheri Caste & Income Certificates",
    "Central & Karnataka State Recruitment Applications",
    "High-Speed Printing, Scanning & Document Lamination",
  ],
};